# write a docker compose file for dotnet 6 and rabbit mq
version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  consumer:
    container_name: url_health_checker
    build:
      context: .
      dockerfile: src/Consumer/Dockerfile
    depends_on:
      - rabbitmq

  producer:
    container_name: url_health_checker
    build:
      context: .
      dockerfile: src/Consumer/Dockerfile
    depends_on:
      - rabbitmq
